<a href="https://colab.research.google.com/github/tbewtrabe24-max/UCS420/blob/main/Assignment3Pandas_1024160070_UCS420.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

#Q1

In [ ]:
data = {
    "Tid": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    "Refund": ["Yes", "No", "No", "Yes", "No", "No", "Yes", "No", "No", "No"],
    "Marital_Status": [
        "Single", "Married", "Single", "Married", "Divorced",
        "Married", "Divorced", "Single", "Married", "Single"
    ],
    "Taxable_Income": [
        "125K", "100K", "70K", "120K", "95K",
        "60K", "220K", "85K", "75K", "90K"
    ],
    "Cheat": ["No", "No", "No", "No", "Yes", "No", "No", "Yes", "No", "Yes"]
}

In [ ]:
df = pd.DataFrame(data)
df

   Tid Refund Marital_Status Taxable_Income Cheat
0    1    Yes         Single           125K    No
1    2     No        Married           100K    No
2    3     No         Single            70K    No
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No
9   10     No         Single            90K   Yes

# Q2

In [ ]:
print(df.loc[[0, 4, 7, 8]])

   Tid Refund Marital_Status Taxable_Income Cheat
0    1    Yes         Single           125K    No
4    5     No       Divorced            95K   Yes
7    8     No         Single            85K   Yes
8    9     No        Married            75K    No

#Q3

In [ ]:
print(df.iloc[3:8])

   Tid Refund Marital_Status Taxable_Income Cheat
3    4    Yes        Married           120K    No
4    5     No       Divorced            95K   Yes
5    6     No        Married            60K    No
6    7    Yes       Divorced           220K    No
7    8     No         Single            85K   Yes

In [ ]:
print(df.iloc[4:9,2:5])

  Marital_Status Taxable_Income Cheat
4       Divorced            95K   Yes
5        Married            60K    No
6       Divorced           220K    No
7         Single            85K   Yes
8        Married            75K    No

In [ ]:
print(df.iloc[:,1:4])

  Refund Marital_Status Taxable_Income
0    Yes         Single           125K
1     No        Married           100K
2     No         Single            70K
3    Yes        Married           120K
4     No       Divorced            95K
5     No        Married            60K
6    Yes       Divorced           220K
7     No         Single            85K
8     No        Married            75K
9     No         Single            90K

#Q4

In [ ]:
path = '/content/Iris.csv'
iris_df = pd.read_csv("Iris.csv")

print("First five rows of Iris dataset:")
print(iris_df.head())

First five rows of Iris dataset:
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

# Q5

In [ ]:
iris_deleted_df = iris_df.drop(index=4).drop(columns=iris_df.columns[3])

In [ ]:
iris_deleted_df

      Id  SepalLengthCm  SepalWidthCm  PetalWidthCm         Species
0      1            5.1           3.5           0.2     Iris-setosa
1      2            4.9           3.0           0.2     Iris-setosa
2      3            4.7           3.2           0.2     Iris-setosa
3      4            4.6           3.1           0.2     Iris-setosa
5      6            5.4           3.9           0.4     Iris-setosa
..   ...            ...           ...           ...             ...
145  146            6.7           3.0           2.3  Iris-virginica
146  147            6.3           2.5           1.9  Iris-virginica
147  148            6.5           3.0           2.0  Iris-virginica
148  149            6.2           3.4           2.3  Iris-virginica
149  150            5.9           3.0           1.8  Iris-virginica

[149 rows x 5 columns]

## Q6

In [ ]:
employee_data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "Diana", "Edward"],
    "Department": ["HR", "IT", "IT", "Marketing", "Sales"],
    "Age": [29, 34, 41, 28, 38],
    "Salary": [50000, 70000, 65000, 55000, 60000],
    "Years_of_Experience": [4, 8, 10, 3, 12],
    "Joining_Date": [
        "2020-03-15",
        "2017-07-19",
        "2013-06-01",
        "2021-02-10",
        "2010-11-25"
    ],
    "Gender": ["Female", "Male", "Male", "Female", "Male"],
    "Bonus": [5000, 7000, 6000, 4500, 5000],
    "Rating": [4.5, 4.0, 3.8, 4.7, 3.5]
}

In [ ]:
employees_df = pd.DataFrame(employee_data)

In [ ]:
employees_df["Joining_Date"] = pd.to_datetime(employees_df["Joining_Date"])

employees_df.to_csv("employees.csv", index=False)

In [ ]:
print(employees_df.shape)

(5, 10)

In [ ]:
print(employees_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      datetime64[ns]
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 532.0+ bytes
None

In [ ]:
print(employees_df.describe())

       Employee_ID        Age       Salary  Years_of_Experience  \
count     5.000000   5.000000      5.00000             5.000000
mean    103.000000  34.000000  60000.00000             7.400000
min     101.000000  28.000000  50000.00000             3.000000
25%     102.000000  29.000000  55000.00000             4.000000
50%     103.000000  34.000000  60000.00000             8.000000
75%     104.000000  38.000000  65000.00000            10.000000
max     105.000000  41.000000  70000.00000            12.000000
std       1.581139   5.612486   7905.69415             3.847077

              Joining_Date   Bonus    Rating
count                    5     5.0  5.000000
mean   2016-08-20 00:00:00  5500.0  4.100000
min    2010-11-25 00:00:00  4500.0  3.500000
25%    2013-06-01 00:00:00  5000.0  3.800000
50%    2017-07-19 00:00:00  5000.0  4.000000
75%    2020-03-15 00:00:00  6000.0  4.500000
max    2021-02-10 00:00:00  7000.0  4.700000
std                    NaN  1000.0  0.494975

In [ ]:
print(employees_df.head()) #first 5

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
0   2020-03-15  Female   5000     4.5
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [ ]:
print(employees_df.tail(3))

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating
2   2013-06-01    Male   6000     3.8
3   2021-02-10  Female   4500     4.7
4   2010-11-25    Male   5000     3.5

In [ ]:
avg_salary = employees_df["Salary"].mean()
total_bonus = employees_df["Bonus"].sum()
youngest_age = employees_df["Age"].min()
highest_rating = employees_df["Rating"].max()

print("Average Salary:", avg_salary)
print("Total Bonus:", total_bonus)
print("Youngest Employee Age:", youngest_age)
print("Highest Performance Rating:", highest_rating)

Average Salary: 60000.0
Total Bonus: 27500
Youngest Employee Age: 28
Highest Performance Rating: 4.7

In [27]:
sorted_salary_df = employees_df.sort_values(by="Salary", ascending=False)

print(sorted_salary_df)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
4          105   Edward      Sales   38   60000                   12
3          104    Diana  Marketing   28   55000                    3
0          101    Alice         HR   29   50000                    4

  Joining_Date  Gender  Bonus  Rating
1   2017-07-19    Male   7000     4.0
2   2013-06-01    Male   6000     3.8
4   2010-11-25    Male   5000     3.5
3   2021-02-10  Female   4500     4.7
0   2020-03-15  Female   5000     4.5

In [28]:
def performance_category(rating):
    if rating >= 4.5:
        return "Excellent"
    elif rating >= 4.0:
        return "Good"
    else:
        return "Average"

employees_df["Performance_Category"] = employees_df["Rating"].apply(
    performance_category
)

print(employees_df[["Name", "Rating", "Performance_Category"]])

      Name  Rating Performance_Category
0    Alice     4.5            Excellent
1      Bob     4.0                 Good
2  Charlie     3.8              Average
3    Diana     4.7            Excellent
4   Edward     3.5              Average

In [29]:
print("Missing values in each column:")
print(employees_df.isnull().sum())

Missing values in each column:
Employee_ID             0
Name                    0
Department              0
Age                     0
Salary                  0
Years_of_Experience     0
Joining_Date            0
Gender                  0
Bonus                   0
Rating                  0
Performance_Category    0
dtype: int64

In [30]:
employees_df.rename(columns={"Employee_ID": "ID"}, inplace=True)

print(employees_df.head())

    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
0  101    Alice         HR   29   50000                    4   2020-03-15
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
3  104    Diana  Marketing   28   55000                    3   2021-02-10
4  105   Edward      Sales   38   60000                   12   2010-11-25

   Gender  Bonus  Rating Performance_Category
0  Female   5000     4.5            Excellent
1    Male   7000     4.0                 Good
2    Male   6000     3.8              Average
3  Female   4500     4.7            Excellent
4    Male   5000     3.5              Average

In [31]:
more_than_5_years = employees_df[
    employees_df["Years_of_Experience"] > 5
]

print("Employees with more than 5 years of experience:")
print(more_than_5_years)

Employees with more than 5 years of experience:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01
4  105   Edward      Sales   38   60000                   12   2010-11-25

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average
4   Male   5000     3.5              Average

In [32]:
it_employees = employees_df[
    employees_df["Department"] == "IT"
]

print("Employees in IT department:")
print(it_employees)

Employees in IT department:
    ID     Name Department  Age  Salary  Years_of_Experience Joining_Date  \
1  102      Bob         IT   34   70000                    8   2017-07-19
2  103  Charlie         IT   41   65000                   10   2013-06-01

  Gender  Bonus  Rating Performance_Category
1   Male   7000     4.0                 Good
2   Male   6000     3.8              Average

In [33]:
employees_df["Tax"] = employees_df["Salary"] * 0.10

print(employees_df[["ID", "Name", "Salary", "Tax"]])

    ID     Name  Salary     Tax
0  101    Alice   50000  5000.0
1  102      Bob   70000  7000.0
2  103  Charlie   65000  6500.0
3  104    Diana   55000  5500.0
4  105   Edward   60000  6000.0

In [34]:
employees_df.to_csv("modified_employees.csv", index=False)

print("Modified employee dataset saved successfully.")

Modified employee dataset saved successfully.